SERVER_DATA = ('127.0.0.1', 8826)
START_MESSEGE = "HELLO"
NUM_OF_BYTES = 1024
from enum import Enum, auto

# request code

# Response Codes
CODE_LOGIN_RESP = 200
CODE_SIGN_UP_RESP = 201
CODE_ERROR_RESPONSE = 202
LOGOUT_RESP = 203
GET_ROOM_RESP = 204
GET_PLAYERS_RESP = 205
JOIN_ROOM_RESP = 206
CREATE_ROOM_RESP = 207
GET_HIGH_SCORE_RESP = 208
GET_PERSONAL_STATS_RESP = 209
CLOSE_ROOM_RESP = 210
START_GAME_RESP = 211
GET_ROOM_STATE_RESP = 212
LEAVE_ROOM_RESP = 213
AM_I_ADMIN_RESP = 214
LEAVE_GAME_RESP = 215
GET_QUESTION_RESP = 216
SUBMIT_ANSWER_RESP = 217
GET_GAME_RESULTS_RESP = 218
ADD_QUESTION_RESP = 219
JOIN_ONE_ON_ONE_RESP = 220

# Request Codes
CODE_LOGIN_REQ = 100
CODE_SIGN_UP_REQ = 101
CODE_ERROR_REQ = 102
LOGOUT_REQ = 103
GET_ROOM_REQ = 104
GET_PLAYERS_REQ = 105
JOIN_ROOM_REQ = 106
CREATE_ROOM_REQ = 107
GET_HIGH_SCORE_REQ = 108
GET_PERSONAL_STATS_REQ = 109
CLOSE_ROOM_REQ = 110
START_GAME_REQ = 111
GET_ROOM_STATE_REQ = 112
LEAVE_ROOM_REQ = 113
AM_I_ADMIN_REQ = 114
LEAVE_GAME_REQ = 115
GET_QUESTION_REQ = 116
SUBMIT_ANSWER_REQ = 117
GET_GAME_RESULT_REQ = 118
ADD_QUESTION_REQ = 119
JOIN_ONE_ON_ONE_REQ = 120

SIZE_OF_LENGTH = 4
FAILED_STATUS = 0
WORK_STATUS = 1
GAME_ENDED = 100

EMAIL: str = "email"
PASSWORD: str = "password"
USER_NAME: str = "username"
ADDRESS: str = "address"
PHONE_NUMBER: str = "phoneNumber"
BIRTH_DATE: str = "birthDate"
ROOM_ID = "roomId"

ROOM_NAME = "roomName"
MAX_USERS = "maxUsers"
QUESTION_COUNT = "questionCount"
ANSOWER_TIMEOUT = "answerTimeout"

HAS_GAME_BEGUN = "hasGameBegun"
PLAYERS = "players"

QUESTION = "question"
ANSWERS = "answers"

ANSWER_ID = "answerId"
